language: node_js
node_js:
- 10.16.0
- 12.7.0
sudo: false
cache: npm
notifications:
  email: false
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
deploy:
  provider: npm
  email: jordan.baczuk@gmail.com
  api_key:
    secure: rNzqhlGjAEvs7nN+UEnjAZpvbYwbpaA20NabadLlukA5HIYprfWkeHIltO4tERB4o94GqKqB7vKaN5CbFH95Nz4QsiCTUzkwCpP5j4vofuac7jSulFoQFz8h8qTPv0SjvwILVcBGGEnvmUNlxVJ95aqp+rKFDyHFj3w92Dn0fHQs02B/uGQI/CWIpX/86sLGpsbrzeZbWrnX6LejUcwgGWkw+JH7Iw/yqOZIeMTJgrERg4PIXnD0U6MEJt/40wSaAEiwVejLasPMgTJaDjITfBJtUWNyzTjKoOtiR+5dfmgQYpiNubzYsMSbxU+AuR+m+cH6d0fXcN8hgs/h1oV8WJBo8ALQfv5IlNJs8SMzyMV5Q857P3OZZboDZAiNo8t9f9DPaEqs6cxtqdRFqONKqaXWl5KrTsH004Med11/hYt527W6JV7gjHaJ73oWdec7YABaiU//r35qbKZy8Dro4kSGi10fq0Hpt4kBM3PtiK6mAd2vQ1IR5x/fIwaCOFNdhJYIN86e2EssZdl2+mlakjuh9FMyxZl6L2sw8oY+kqFqxk5QM3tfpGdRkA3NbwSUsMDrpdfCWFR6iOfhWpbeyEKzlcnjgXwjV3SLDcgZHw3aSuyr7PXqDplGlEtniNLbA71Vt58IWfPeJ6bTaxrlLnFAntQESwDIgZKQwDsBC04=
  on:
    repo: JBaczuk/burst
    branch: master
