language: node_js
node_js:
- "10"
- "12"
sudo: false
cache: npm
notifications:
  email: false
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: jordan.baczuk@gmail.com
  api_key:
    secure: dt5hupj9TIhzaOFkogC/PMbQMmhErscRX9Las+kFZJyJ6lcd/ny36AzChrhVg06i++qE6t0cTHCbexwwdq2N+xktX1QcFySfHQna9vOUvxyVHwQBbX7aOPplnmIZoo8Gn1a9wWXHJaTkSkWIjxByTneLBqn8iIxrAl1nslimuO+/1yvjcVHBeoXBC+nt+T1EWYZIeytWVINJuPnI6487whCfoi67wukfzoWwgfhm3VT3VeQAIPfHfMK5tJWoiPQj4/03mpIyYfMtDc105+1YhNeIxhTO2vkB08lLC87/7h63vG4N/2bQ0UIL+mdq2pMFF5sryjpNWRrZTW843atBEWxSa3sZUB7hkTY0Om0SYmRwpRr9YJJT4gI3d7J84/xIm7METog5vNFHrSiK+mmcPjR9n14YU5JXnDCG0sOEs61rPkKtQptP5NqapNEC1OwzKLk7iFJtMcVCcjfx7MxaUSBPeAF6ogJeJ+ldZMF9cOdaIhsTJxPyI4wTse7CjJgzZlTQ99C0UarD5g3+EOY9VUEXG+2NA+kyJ7l8G5E4nlSz7yheGhVEtUsb+0koFYvd9RJyMYXBVZqAjHuu5YQZ+ItY8xk8ivs7uQ2keP+vfDCCtmtwdbpxjELZmL9MJJKCJAnQE4Y0rJ1DsjIPiHVRc17Tz2IMwOu43HOsD1jbByM=
  on:
    repo: JBaczuk/burst-log
    branch: master
